### ISSUE TITLE
Bounds on /slice

### ISSUE THREAD

**Issue by ErlendHaa** [equinor/vds-slice#94]
Implement API support for asking for sub-slices.

**Comment by achaikou** [comment]
PO likes just adding bounds parameter to user request (current direction and lineno stay intact)

bounds (or something) can have one or two lines - one for each dimension to be bound. 
Current consistency with other places might suggest having min-max bounds as a tuple/array instead of separate min/max values. That might require user supplying both bounds even if they are actually interested in just min or max bound. (How likely/annoying is this needs to be considered)

Current solution expects a lot of error messages returned to the user as user is kinda needs to know which keys are allowed to be supplied.
For example, if direction is inline, then bounds should also be provided in annotation coordinates. Index should raise.
Supplying something twice should also scream.
Supplying depth instead of time and the other way around should also scream.
etc.

Something like

```
direction: inline
lineno: 98
bounds:
  depth: [12, 90] //raise if this is time. raise if you supply here I, K or J.
  //xline: [45, 89] is not required. Just one dimension is enough
```
